# Generated by Django 5.2 on 2026-04-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('header', models.TextField(blank=True, help_text="Text before the reply (e.g., 'Dear {{customer_name}},')")),
                ('footer', models.TextField(blank=True, help_text="Text after the reply (e.g., 'Best regards, {{agent_name}}')")),
                ('separator', models.CharField(default='\n\n', help_text='Separator between sections', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
            },
        ),
    ]
