# Generated by Django 5.2 on 2026-02-28 12:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_apikey_userpreference_alter_user_options_and_more'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TicketChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(help_text='Higher number = higher priority', unique=True)),
                ('color', models.CharField(blank=True, help_text='CSS color code', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_closed_state', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('system', 'System')], max_length=10)),
                ('sender_name', models.CharField(blank=True, help_text='Denormalised name', max_length=200)),
                ('content', models.TextField()),
                ('content_type', models.CharField(default='text', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal_note', models.BooleanField(default=False)),
                ('sender_user', models.ForeignKey(blank=True, help_text='If sender is an agent', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('hash', models.CharField(blank=True, help_text='SHA‑256 hash', max_length=64)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.message')),
            ],
        ),
        migrations.CreateModel(
            name='SlaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=200)),
                ('response_hours', models.PositiveIntegerField(help_text='Target hours for first response')),
                ('resolution_hours', models.PositiveIntegerField(help_text='Target hours for resolution')),
                ('business_hours_only', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.businesscalendar')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_rules', to='tickets.ticketpriority')),
            ],
        ),
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger_event', models.CharField(choices=[('response_breach', 'After response SLA breach'), ('resolution_breach', 'After resolution SLA breach'), ('time_since_creation', 'After fixed time from creation'), ('time_since_assignment', 'After fixed time from assignment'), ('no_activity', 'After period of no activity')], max_length=30)),
                ('threshold_minutes', models.PositiveIntegerField(blank=True, help_text='Used with time‑based triggers', null=True)),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Escalation level')),
                ('escalate_to_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.role')),
                ('escalate_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sla_rule', models.ForeignKey(blank=True, help_text='If linked to a specific SLA rule', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.slarule')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_contact', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('external_reference_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('source_system', models.CharField(blank=True, choices=[('web', 'Web Portal'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Phone Call'), ('sap', 'SAP'), ('as400', 'AS400'), ('api', 'External API')], max_length=20)),
                ('response_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0)),
                ('is_response_breached', models.BooleanField(default=False)),
                ('is_resolution_breached', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('erp_sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('erp_last_sync', models.DateTimeField(blank=True, null=True)),
                ('erp_error_message', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, help_text='Dynamic category fields', null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.department')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket'),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticketcategory'),
        ),
        migrations.CreateModel(
            name='TicketCategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_key', models.CharField(help_text='Used in JSON keys', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('multi_select', 'Multi-select'), ('date', 'Date'), ('file', 'File')], max_length=20)),
                ('choices', models.JSONField(blank=True, help_text='For select/multi-select: list of {value, label}', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tickets.ticketcategory')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticketchannel'),
        ),
        migrations.CreateModel(
            name='TicketEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=500)),
                ('is_resolved', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField()),
                ('escalated_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-escalated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.tickettrackingtoken')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tickets.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticketpriority'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticketstatus'),
        ),
        migrations.CreateModel(
            name='TicketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('comment', 'Comment'), ('status_change', 'Status Change'), ('priority_change', 'Priority Change'), ('department_change', 'Department Change'), ('assignment_change', 'Assignment Change'), ('category_change', 'Category Change'), ('other', 'Other')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department')),
                ('new_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.ticketpriority')),
                ('new_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.ticketstatus')),
                ('old_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('old_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department')),
                ('old_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.ticketpriority')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.ticketstatus')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tickets.ticket')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHourRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_working', models.BooleanField(default=True, help_text='False for non-working day (e.g., weekend)')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_rules', to='tickets.businesscalendar')),
            ],
            options={
                'unique_together': {('calendar', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('is_working', models.BooleanField(default=False, help_text="True if it's an extra working day, False for holiday")),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tickets.businesscalendar')),
            ],
            options={
                'unique_together': {('calendar', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['ticket', 'sent_at'], name='tickets_mes_ticket__92be07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketcategoryfield',
            unique_together={('category', 'field_key')},
        ),
        migrations.AddIndex(
            model_name='slarule',
            index=models.Index(fields=['is_active'], name='tickets_sla_is_acti_ac83df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slarule',
            unique_together={('priority', 'department')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='tickets_tic_ticket__bf3905_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['uuid'], name='tickets_tic_uuid_33f119_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer'], name='tickets_tic_custome_c66646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status__20eacd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to'], name='tickets_tic_assigne_bcac0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['response_due_at'], name='tickets_tic_respons_3d0026_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['resolution_due_at'], name='tickets_tic_resolut_89b4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['external_reference_id'], name='tickets_tic_externa_ab8c93_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['erp_sync_status'], name='tickets_tic_erp_syn_337f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketupdate',
            index=models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__9ee4c7_idx'),
        ),
    ]
