# Generated by Django 5.2 on 2026-03-19 09:47
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='escalate_to_role',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='escalate_to_user',
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-19 09:47:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='escalationpolicy',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Escalation level (1=first, 2=second, etc.)'),
        ),
        migrations.AlterModelOptions(
            name='escalationpolicy',
            options={'ordering': ['level', 'name'], 'verbose_name_plural': 'Escalation Policies'},
        ),
        migrations.CreateModel(
            name='EscalationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_template', models.CharField(blank=True, help_text='Optional template name for notifications', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order within same policy level (if multiple targets)')),
                ('escalate_to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.department')),
                ('escalate_to_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.role')),
                ('escalate_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='tickets.escalationpolicy')),
            ],
            options={
                'ordering': ['policy__level', 'order'],
                'unique_together': {('policy', 'order')},
            },
        ),
    ]