# Generated by Django 5.2 on 2026-04-11 08:26

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to=tickets.models.message_attachment_upload_to),
        ),
    ]
