# Generated by Django 5.2 on 2026-03-23 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tickets', '0002_escalation_matrix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalationpolicy',
            options={'ordering': ['level', 'trigger_event'], 'verbose_name_plural': 'Escalation Policies'},
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='escalate_to_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.role'),
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='escalate_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalation_policies', to=settings.AUTH_USER_MODEL),
        ),
    ]
