# Generated by Django 5.2 on 2026-03-19 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('tickets_opened', models.IntegerField(default=0)),
                ('tickets_resolved', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(blank=True, null=True)),
                ('avg_resolution_time', models.FloatField(blank=True, null=True)),
                ('breached_response', models.IntegerField(default=0)),
                ('breached_resolution', models.IntegerField(default=0)),
                ('escalated_tickets', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TicketMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_response_time', models.PositiveIntegerField(blank=True, help_text='Seconds from creation to first agent response', null=True)),
                ('resolution_time', models.PositiveIntegerField(blank=True, help_text='Seconds from creation to resolution', null=True)),
                ('time_to_assign', models.PositiveIntegerField(blank=True, help_text='Seconds from creation to first assignment', null=True)),
                ('escalation_count', models.PositiveSmallIntegerField(default=0)),
                ('reassignment_count', models.PositiveSmallIntegerField(default=0)),
                ('message_count', models.PositiveSmallIntegerField(default=0)),
                ('agent_message_count', models.PositiveSmallIntegerField(default=0)),
                ('customer_message_count', models.PositiveSmallIntegerField(default=0)),
                ('sla_breached_response', models.BooleanField(default=False)),
                ('sla_breached_resolution', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='tickets.ticket')),
            ],
            options={
                'verbose_name_plural': 'Ticket metrics',
            },
        ),
    ]
