# Generated by Django 5.2 on 2026-02-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_response_time', models.PositiveIntegerField(blank=True, help_text='Seconds from creation to first agent response', null=True)),
                ('resolution_time', models.PositiveIntegerField(blank=True, help_text='Seconds from creation to resolution', null=True)),
                ('time_to_assign', models.PositiveIntegerField(blank=True, help_text='Seconds from creation to first assignment', null=True)),
                ('escalation_count', models.PositiveSmallIntegerField(default=0)),
                ('reassignment_count', models.PositiveSmallIntegerField(default=0)),
                ('message_count', models.PositiveSmallIntegerField(default=0)),
                ('agent_message_count', models.PositiveSmallIntegerField(default=0)),
                ('customer_message_count', models.PositiveSmallIntegerField(default=0)),
                ('sla_breached_response', models.BooleanField(default=False)),
                ('sla_breached_resolution', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ticket metrics',
            },
        ),
    ]
