<<<<<<< Updated upstream
# Generated by Django 5.2 on 2026-04-02 06:43
=======
# Generated by Django 5.2 on 2026-03-05 06:07
>>>>>>> Stashed changes

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketchannel'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['external_reference'], name='customers_c_externa_61443e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customercontact',
            unique_together={('customer', 'contact_type', 'value')},
        ),
    ]
