# Generated by Django 5.2 on 2026-03-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicticketsubmission',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticketcategory'),
        ),
        migrations.AddField(
            model_name='tickettrackingtoken',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_token', to='tickets.ticket'),
        ),
    ]
